apiVersion: v1
kind: Pod
metadata:
  name: content-manager
spec:
  containers:
  - name: content-manager
    image: busybox
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: web-content
      mountPath: /content
  volumes:
  - name: web-content
    persistentVolumeClaim:
      claimName: web-content-pvc